### ISSUE TITLE
Run tests without an internet connection required

### ISSUE THREAD

**Issue by jschomay** [benansell/lobo#1]
First, fantastic tool!  I love it.

One sticky point for me - I often code on the bus, where I have no wifi.  I noticed today that lobo does some kind of package check before running any tests, which results in an error, meaning, I can't run my tests if I'm offline.  I know elm-test node runner works offline, so I'm hoping you can make lobo work offline too.  Maybe give a warning, but still run the tests.

Here is the specific output:

```
-----------------------------------[ BUILD ]------------------------------------
Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18&since=2017-03-03%2001%3A17%3A11.4254%20UTC>

FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (nodename nor servname provided, or not known)

----------------------------------[ WAITING ]-----------------------------------
```

Thanks!!

**Comment by benansell** [comment]
Thanks for the info and I am glad you like Lobo. I feel your pain working without internet connection during a commute. 
I will push a fix for this over the weekend, hopefully you will then be able to try it out next week.

**Comment by benansell** [comment]
@jschomay I have added a new option call "--noInstall" that stops elm-package from running when executing the tests.   

Hopefully when you update your copy of lobo to the latest version this should allow you to run the tests offline.

**Comment by jschomay** [comment]
Yes, works great, thank you!
