### ISSUE TITLE
Collect output for each test

### ISSUE THREAD

**Issue by pbiggar** [benansell/lobo#15]
When tests fail, it would be great to see the output for the test printed out in the summary. Perhaps an option like --showTodo and --showSkip (which are why we moved to lobo).

**Comment by benansell** [comment]
@pbiggar are you thinking of an option that produces an output similar to --showTodo / --showSkip but for failing tests but then also prints out the full details after the list of failing tests?

For example something like the following:

<img width="605" alt="lobo 15-example" src="https://user-images.githubusercontent.com/684667/31874735-b52e780e-b7c2-11e7-8d7c-99302ebf5c6e.png">

**Comment by pbiggar** [comment]
Yeah, similar to that. So for example, if test 3 had any `Debug.log` output, it would print it at the bottom of that screenshot, either before or after the Expectation info.

**Comment by benansell** [comment]
Ok, so how about keeping the original summary, but capturing all the Debug.log statements for a test and not reporting them until after the after the expectation like this:
<img width="568" alt="lobo 14-example-2" src="https://user-images.githubusercontent.com/684667/31926880-46223bfe-b889-11e7-8292-aa0670c1984f.png">

where in the above example the log statements are:
: foo bar
: baz

and
: qux

**Comment by pbiggar** [comment]
Yes, this would be perfect.

Note that we've switched back to elm-test after a brief trial of lobo, so we're not blocked by this (though I think this would have been a good reason to stay).

**Comment by benansell** [comment]
This is now available via npm in lobo v0.4.0
