### ISSUE TITLE
Prompt does not accept default argument

### ISSUE THREAD

**Issue by kevgathuku** [benansell/lobo#2]
Hello and thanks for creating lobo.
When adding lobo to an existing project with tests, the CLI prompt doesn't accept the default argument 
```
The source-directories of the test elm-package.json needs to be updated to contain:
../node_modules/lobo/runner
../node_modules/lobo/plugin/elm-test-extra

May I add them to elm-package.json for you? (Y/n)
```
After this prompt, I expected that if I press the `Enter` key, the default value of `Y` should be chosen, rather than having me manually input the `Y`.
However, that is not currently implemented.

**Comment by benansell** [comment]
@kevgathuku thanks for the suggestion, sorry for the delay in looking at this issue - I believe the latest version (0.2.1) should work as you suggested. Please let me know if it does not.
