### ISSUE TITLE
Support to find all Tests?

### ISSUE THREAD

**Issue by squaresurf** [benansell/lobo#23]
I've been using elm-test and the node runner while we took care of a few lobo issues. I do prefer lobo for 2 main reasons:

1. it will watch even if the build fails on the initial run ([elm-test is working on this](https://github.com/rtfeldman/node-test-runner/issues/204))
1. it will manage test deps while running/watching while elm-test requires a separate command

One thing I have come to depend on elm-test for though, is the fact that it will find all functions with the `Test` type. It will warn if a top level module has a function with that type and doesn't expose it. It will also automatically run them nested in a describe named after the module's name. It's been nice to break up my tests without having to roll them up into the main Test module. Is this sort of behavior something you would consider adding to lobo?

p.s. Thank you for your work on lobo.

**Comment by benansell** [comment]
Thank you for the feedback on which features you find useful - I always find that interesting.

Yes I have thought about adding support to include test discovery, but I had originally postponed it to coincide with upgrade to elm 0.19 - but I am happy to bring that feature forwards, I will have a look at implementing it and update this issue accordingly.

**Comment by squaresurf** [comment]
I just refactored my tests to roll all my tests up for lobo so this isn't a huge priority to me, but it will be nice for the sake of compatibility to have done at some point.

**Comment by squaresurf** [comment]
I just tested this out and it works great!
