### ISSUE TITLE
Why not contribute upstream?

### ISSUE THREAD

**Issue by eeue56** [benansell/lobo#8]
Hi there! 

This is a cool library, with some cool features. However, the defacto test runner will be shipped under `elm-test`. It would be awesome for the entire Elm community to add any features you thought were missing to elm-test, rather than go it alone where less people get to see some of the things you have. Come chat to us on #testing on the [Elm Slack channel](https://elmlang.slack.com/), and we can discuss!

Cheers,
eeue56

**Comment by benansell** [comment]
Noah it's good to here that you like some of the features. I am not on slack very often but will be sure to say hello on #testing next time I am logged on.

**Comment by eeue56** [comment]
Please do. It'll be the best way to get some of these changes into the actual `elm-test` runner!
